import Head from 'next/head'
import Image from 'next/image'
import Hero from '../../Components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Banana</title>
        <meta name='Description' content='Generated by create app'/>
        <link rel='icon' href='/favicon' />
      </Head>
      {/* Landing Page */}
      <Hero/>
    </div>

  )
}
